export const ellipse1 = require('./ellipse1.png')
export const ellipse3 = require('./ellipse3.png')
export const google = require('./google.png')
export const welcome1 = require('./welcome1.png')
export const welcome2 = require('./welcome2.png')
export const welcome3 = require('./welcome3.png')
